package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente extends RecursiveTreeObject<Cliente>  implements java.io.Serializable {


     private int clienteId;
     private TipoCliente tipoCliente;
     private String ruc;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String telefono;
     private Set facturas = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set prestamoAhorros = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int clienteId, TipoCliente tipoCliente, String ruc, String nombres) {
        this.clienteId = clienteId;
        this.tipoCliente = tipoCliente;
        this.ruc = ruc;
        this.nombres = nombres;
    }
    public Cliente(int clienteId, TipoCliente tipoCliente, String ruc, String nombres, String apellidos, String direccion, String telefono, Set facturas, Set pedidos, Set prestamoAhorros) {
       this.clienteId = clienteId;
       this.tipoCliente = tipoCliente;
       this.ruc = ruc;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.facturas = facturas;
       this.pedidos = pedidos;
       this.prestamoAhorros = prestamoAhorros;
    }
   
    public int getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(int clienteId) {
        this.clienteId = clienteId;
    }
    public TipoCliente getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(TipoCliente tipoCliente) {
        this.tipoCliente = tipoCliente;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getPrestamoAhorros() {
        return this.prestamoAhorros;
    }
    
    public void setPrestamoAhorros(Set prestamoAhorros) {
        this.prestamoAhorros = prestamoAhorros;
    }

    @Override
    public String toString() {
        return nombres + " " + apellidos;
    }

   



}


