package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento  implements java.io.Serializable {


     private int tiendaId;
     private String razonSocial;
     private String ruc;
     private String direccion;
     private String correo;
     private String telefono;
     private Set inventarios = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Establecimiento() {
    }

	
    public Establecimiento(int tiendaId, String razonSocial, String ruc, String direccion) {
        this.tiendaId = tiendaId;
        this.razonSocial = razonSocial;
        this.ruc = ruc;
        this.direccion = direccion;
    }
    public Establecimiento(int tiendaId, String razonSocial, String ruc, String direccion, String correo, String telefono, Set inventarios, Set facturas) {
       this.tiendaId = tiendaId;
       this.razonSocial = razonSocial;
       this.ruc = ruc;
       this.direccion = direccion;
       this.correo = correo;
       this.telefono = telefono;
       this.inventarios = inventarios;
       this.facturas = facturas;
    }
   
    public int getTiendaId() {
        return this.tiendaId;
    }
    
    public void setTiendaId(int tiendaId) {
        this.tiendaId = tiendaId;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }

    @Override
    public String toString() {
        return razonSocial;
    }

    



}


