package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;




/**
 * Inventario generated by hbm2java
 */
public class Inventario extends RecursiveTreeObject<Inventario> implements java.io.Serializable {


     private int inventarioId;
     private Establecimiento establecimiento;
     private Producto producto;
     private int cantidad;

    public Inventario() {
    }

    public Inventario(int inventarioId, Establecimiento establecimiento, Producto producto, int cantidad) {
       this.inventarioId = inventarioId;
       this.establecimiento = establecimiento;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public int getInventarioId() {
        return this.inventarioId;
    }
    
    public void setInventarioId(int inventarioId) {
        this.inventarioId = inventarioId;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


