package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OrdenProducto generated by hbm2java
 */
public class OrdenProducto  implements java.io.Serializable {


     private int ordenProductoId;
     private Orden orden;
     private Producto producto;
     private int cantidad;
     private Set recepcionProductos = new HashSet(0);

    public OrdenProducto() {
    }

	
    public OrdenProducto(int ordenProductoId, Orden orden, Producto producto, int cantidad) {
        this.ordenProductoId = ordenProductoId;
        this.orden = orden;
        this.producto = producto;
        this.cantidad = cantidad;
    }
    public OrdenProducto(int ordenProductoId, Orden orden, Producto producto, int cantidad, Set recepcionProductos) {
       this.ordenProductoId = ordenProductoId;
       this.orden = orden;
       this.producto = producto;
       this.cantidad = cantidad;
       this.recepcionProductos = recepcionProductos;
    }
   
    public int getOrdenProductoId() {
        return this.ordenProductoId;
    }
    
    public void setOrdenProductoId(int ordenProductoId) {
        this.ordenProductoId = ordenProductoId;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getRecepcionProductos() {
        return this.recepcionProductos;
    }
    
    public void setRecepcionProductos(Set recepcionProductos) {
        this.recepcionProductos = recepcionProductos;
    }




}


