package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orden generated by hbm2java
 */
public class Orden extends RecursiveTreeObject<Orden> implements java.io.Serializable {


     private int ordenId;
     private Proveedor proveedor;
     private Date fecha;
     private String observaciones;
     private Boolean estado;
     private Set ordenProductos = new HashSet(0);

    public Orden() {
    }

	
    public Orden(int ordenId, Proveedor proveedor, Date fecha) {
        this.ordenId = ordenId;
        this.proveedor = proveedor;
        this.fecha = fecha;
    }
    public Orden(int ordenId, Proveedor proveedor, Date fecha, String observaciones, Boolean estado, Set ordenProductos) {
       this.ordenId = ordenId;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.observaciones = observaciones;
       this.estado = estado;
       this.ordenProductos = ordenProductos;
    }
   
    public int getOrdenId() {
        return this.ordenId;
    }
    
    public void setOrdenId(int ordenId) {
        this.ordenId = ordenId;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getOrdenProductos() {
        return this.ordenProductos;
    }
    
    public void setOrdenProductos(Set ordenProductos) {
        this.ordenProductos = ordenProductos;
    }




}


