package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int pagoId;
     private PrestamoAhorro prestamoAhorro;
     private String descripcion;
     private BigDecimal monto;

    public Pago() {
    }

	
    public Pago(int pagoId, PrestamoAhorro prestamoAhorro, BigDecimal monto) {
        this.pagoId = pagoId;
        this.prestamoAhorro = prestamoAhorro;
        this.monto = monto;
    }
    public Pago(int pagoId, PrestamoAhorro prestamoAhorro, String descripcion, BigDecimal monto) {
       this.pagoId = pagoId;
       this.prestamoAhorro = prestamoAhorro;
       this.descripcion = descripcion;
       this.monto = monto;
    }
   
    public int getPagoId() {
        return this.pagoId;
    }
    
    public void setPagoId(int pagoId) {
        this.pagoId = pagoId;
    }
    public PrestamoAhorro getPrestamoAhorro() {
        return this.prestamoAhorro;
    }
    
    public void setPrestamoAhorro(PrestamoAhorro prestamoAhorro) {
        this.prestamoAhorro = prestamoAhorro;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


