package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PedidoProducto generated by hbm2java
 */
public class PedidoProducto  implements java.io.Serializable {


     private int pedidoProductoId;
     private Pedido pedido;
     private Producto producto;
     private int cantidad;
     private Set ventas = new HashSet(0);

    public PedidoProducto() {
    }

	
    public PedidoProducto(int pedidoProductoId, Pedido pedido, Producto producto, int cantidad) {
        this.pedidoProductoId = pedidoProductoId;
        this.pedido = pedido;
        this.producto = producto;
        this.cantidad = cantidad;
    }
    public PedidoProducto(int pedidoProductoId, Pedido pedido, Producto producto, int cantidad, Set ventas) {
       this.pedidoProductoId = pedidoProductoId;
       this.pedido = pedido;
       this.producto = producto;
       this.cantidad = cantidad;
       this.ventas = ventas;
    }
   
    public int getPedidoProductoId() {
        return this.pedidoProductoId;
    }
    
    public void setPedidoProductoId(int pedidoProductoId) {
        this.pedidoProductoId = pedidoProductoId;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


