package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido extends RecursiveTreeObject<Pedido> implements java.io.Serializable {


     private int pedidoId;
     private Cliente cliente;
     private Date fecha;
     private Boolean estado;
     private Set pedidoProductos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int pedidoId, Cliente cliente, Date fecha) {
        this.pedidoId = pedidoId;
        this.cliente = cliente;
        this.fecha = fecha;
    }
    public Pedido(int pedidoId, Cliente cliente, Date fecha, Boolean estado, Set pedidoProductos) {
       this.pedidoId = pedidoId;
       this.cliente = cliente;
       this.fecha = fecha;
       this.estado = estado;
       this.pedidoProductos = pedidoProductos;
    }
   
    public int getPedidoId() {
        return this.pedidoId;
    }
    
    public void setPedidoId(int pedidoId) {
        this.pedidoId = pedidoId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getPedidoProductos() {
        return this.pedidoProductos;
    }
    
    public void setPedidoProductos(Set pedidoProductos) {
        this.pedidoProductos = pedidoProductos;
    }




}


