package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PrestamoAhorro generated by hbm2java
 */
public class PrestamoAhorro  implements java.io.Serializable {


     private int creditoId;
     private Cliente cliente;
     private String tipo;
     private String descripcion;
     private BigDecimal monto;
     private Set pagos = new HashSet(0);

    public PrestamoAhorro() {
    }

	
    public PrestamoAhorro(int creditoId, Cliente cliente) {
        this.creditoId = creditoId;
        this.cliente = cliente;
    }
    public PrestamoAhorro(int creditoId, Cliente cliente, String tipo, String descripcion, BigDecimal monto, Set pagos) {
       this.creditoId = creditoId;
       this.cliente = cliente;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.monto = monto;
       this.pagos = pagos;
    }
   
    public int getCreditoId() {
        return this.creditoId;
    }
    
    public void setCreditoId(int creditoId) {
        this.creditoId = creditoId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


