package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto extends RecursiveTreeObject<Producto> implements java.io.Serializable {


     private int productoId;
     private Categoria categoria;
     private Proveedor proveedor;
     private String nombre;
     private String descripcion;
     private Boolean descontinuado;
     private BigDecimal costo;
     private BigDecimal utilidad;
     private Set ordenProductos = new HashSet(0);
     private Set pedidoProductos = new HashSet(0);
     private Set inventarios = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int productoId, Categoria categoria, Proveedor proveedor, String nombre) {
        this.productoId = productoId;
        this.categoria = categoria;
        this.proveedor = proveedor;
        this.nombre = nombre;
    }
    public Producto(int productoId, Categoria categoria, Proveedor proveedor, String nombre, String descripcion, Boolean descontinuado, BigDecimal costo, BigDecimal utilidad, Set ordenProductos, Set pedidoProductos, Set inventarios) {
       this.productoId = productoId;
       this.categoria = categoria;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.descontinuado = descontinuado;
       this.costo = costo;
       this.utilidad = utilidad;
       this.ordenProductos = ordenProductos;
       this.pedidoProductos = pedidoProductos;
       this.inventarios = inventarios;
    }
   
    public int getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(int productoId) {
        this.productoId = productoId;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getDescontinuado() {
        return this.descontinuado;
    }
    
    public void setDescontinuado(Boolean descontinuado) {
        this.descontinuado = descontinuado;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public BigDecimal getUtilidad() {
        return this.utilidad;
    }
    
    public void setUtilidad(BigDecimal utilidad) {
        this.utilidad = utilidad;
    }
    public Set getOrdenProductos() {
        return this.ordenProductos;
    }
    
    public void setOrdenProductos(Set ordenProductos) {
        this.ordenProductos = ordenProductos;
    }
    public Set getPedidoProductos() {
        return this.pedidoProductos;
    }
    
    public void setPedidoProductos(Set pedidoProductos) {
        this.pedidoProductos = pedidoProductos;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }

    @Override
    public String toString() {
        return  nombre;
    }
    
    



}


