package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1


import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor extends RecursiveTreeObject<Proveedor> implements java.io.Serializable {


     private int proveedorId;
     private String razonSocial;
     private String ruc;
     private String ciudad;
     private String direccion;
     private String telefono;
     private Set ordens = new HashSet(0);
     private Set productos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int proveedorId, String razonSocial) {
        this.proveedorId = proveedorId;
        this.razonSocial = razonSocial;
    }
    public Proveedor(int proveedorId, String razonSocial, String ruc, String ciudad, String direccion, String telefono, Set ordens, Set productos) {
       this.proveedorId = proveedorId;
       this.razonSocial = razonSocial;
       this.ruc = ruc;
       this.ciudad = ciudad;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ordens = ordens;
       this.productos = productos;
    }
   
    public int getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(int proveedorId) {
        this.proveedorId = proveedorId;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set ordens) {
        this.ordens = ordens;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }

    @Override
    public String toString() {
        return razonSocial;
    }

    


}


