package modelo;
// Generated 18/08/2019 04:31:36 PM by Hibernate Tools 4.3.1



/**
 * RecepcionProducto generated by hbm2java
 */
public class RecepcionProducto  implements java.io.Serializable {


     private int recepcionId;
     private OrdenProducto ordenProducto;
     private int cantidadReceptada;

    public RecepcionProducto() {
    }

    public RecepcionProducto(int recepcionId, OrdenProducto ordenProducto, int cantidadReceptada) {
       this.recepcionId = recepcionId;
       this.ordenProducto = ordenProducto;
       this.cantidadReceptada = cantidadReceptada;
    }
   
    public int getRecepcionId() {
        return this.recepcionId;
    }
    
    public void setRecepcionId(int recepcionId) {
        this.recepcionId = recepcionId;
    }
    public OrdenProducto getOrdenProducto() {
        return this.ordenProducto;
    }
    
    public void setOrdenProducto(OrdenProducto ordenProducto) {
        this.ordenProducto = ordenProducto;
    }
    public int getCantidadReceptada() {
        return this.cantidadReceptada;
    }
    
    public void setCantidadReceptada(int cantidadReceptada) {
        this.cantidadReceptada = cantidadReceptada;
    }




}


